name: wp-lando-app
recipe: pantheon
services:
  appserver:
    build_as_root:
      - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - chmod +x wp-cli.phar
      - mv -f wp-cli.phar /usr/local/bin/wp
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null
      - echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update -y
      - apt-get install -y nodejs yarn
      - npm install -g npm@latest
    build:
      - cd /app && composer install -n
    run_as_root:
  node:
    type: node
tooling:
  node:
    service: appserver
  npm:
    service: appserver
  yarn:
    service: appserver
  wp:
    service: appserver
config:
  cache: false
