name: wp-lando-app
recipe: pantheon
services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt update -y
      - apt-get install -y nodejs
      - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null
      - echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install yarn
    build:
      - cd /app && composer install
  node:
    type: node
tooling:
  node:
    service: appserver
  npm:
    service: appserver
  yarn:
    service: appserver
config:
  cache: false
